# File generated by Flopy version 3.6.0.dev0 on 02/07/2024 at 20:14:53.
BEGIN attributes
  NAMES  CHDHEAD
  METHODS  LINEAREND
END attributes

BEGIN timeseries
       0.00000000       0.00000000
     307.00000000       1.00000000
     791.00000000       5.00000000
    1000.00000000       2.00000000
END timeseries

