[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "xmf6"
version = "0.1.0"
description = "Biblioteca con herramientas para MODFLOW 6 y Flopy."
authors = [{ name = "Luis Miguel de la Cruz Salas", email = "luiggi@igeofisica.unam.mx" }]
readme = "README.md"
dependencies = ["flopy", "colorama"]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["xmf6", "xmf6.gwf"]
#license-files = ["MIT"]

[tool.setuptools.package-data]
"biblio" = ["../examples/*"]
